### PR TITLE
Made Net::getResults() return by value.

### PR DESCRIPTION
**Pull request by MagaRita**
getResult() function returns by value

### CODE REVIEW

**Comment by heinsaar** [comment]
Excellent, Rita - I just changed the title to the issue's (with 'Make...' into 'Made...'). We've agreed to use actual issue titles to recognize changes quickly and for consistency.

Davit will merge, as always.

**Comment by heinsaar** [comment]
Rita, please make the necessary changes in main.cpp, where the function is used:
```myNet.getResults(resultVals);```

Otherwise you changes won't compile.

**Comment by MagaRita** [comment]
I'll make changes in main.cpp and I have to make changes in Net.h too, right?

**Comment by heinsaar** [comment]
Exactly - in Net.h too.
When you change any function, you have to change all the references to it everywhere in the code, or it won't compile.

**Pull request merged**
